variables:
  DOCKER_DRIVER: overlay2

cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/

stages:
  - build
  - deploy

build: 
  stage: build
  image: node:14.3.0-alpine
  script:
    - npm i
    - npm run build
  artifacts:
    - ./public
  tags: 
    - docker  

deploy: 
  stage: deploy
  image: node:14.3.0-alpine
  script: 
    - npm i 
    - npm run deploy
  tags: 
    - docker
